### ISSUE TITLE
Exception thrown on first time entering VAB (only appeared once)

### ISSUE THREAD

**Issue by smjjames** [ihsoft/KIS#1]
It might be something harmless though and it hasn't appeared again.

Edit: Actually, it'll appear when you first start up KSP and enter the VAB/SPH (as I saw after that odd crash), but it doesn't show up again, not even exiting and reloading the save.

NullReferenceException: Object reference not set to an instance of an object
  at KIS.KISAddonPickup.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
AddonLoader:StartAddons(Startup)
AddonLoader:OnLevelWasLoaded(Int32)

**Comment by enceos** [comment]
I see this exception first time entering VAB, appears only once during each play:

> AddonLoader: Instantiating addon 'KSExperienceTrackerEvents' from assembly 'KerbalStats'
> 
> (Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)
> 
> AddonLoader: Instantiating addon 'KISAddonPickup' from assembly 'KIS'
> 
> (Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)
> 
> NullReferenceException: Object reference not set to an instance of an object
>   at KIS.KISAddonPickup.Awake () [0x00000] in <filename unknown>:0 
> UnityEngine.GameObject:Internal_AddComponentWithType(Type)
> UnityEngine.GameObject:AddComponent(Type)
> AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
> AddonLoader:StartAddons(Startup)
> AddonLoader:OnLevelWasLoaded(Int32)

My output log: https://www.dropbox.com/s/1bavsdnk427wied/output_log19.rar?dl=0

**Comment by KospY** [comment]
Fixed for the next version :)
