### ISSUE TITLE
Problem with attaching "Modular Grider Adapter" to "BZ-52 Radial Attachment Point"

### ISSUE THREAD

**Issue by Peteka** [ihsoft/KIS#100]
If I try to attach the MGA to the BZ-52 it seems like its attached (and I can attach other onto it) but the MGA gets cloned and dissapers after a while.

**Comment by ihsoft** [comment]
Could you please provide a screenshot with the layout you're trying to make? Have you attached MGA to the body in editor or via KIS? If the latter then have you moved it from another place of the vessel or brought out from an inventory? Checking logs (Alt+F12) may also can help.

**Comment by Peteka** [comment]
I can work around the problem, if I place the part first somewhere on my ship and then attaching it to the Radial Attachment Point.

**Comment by Peteka** [comment]
placing the parts on the ship and than attatching it solved it for me.

Am 19.02.2016 um 05:42 schrieb ihsoft:
