### ISSUE TITLE
item specific storage

### ISSUE THREAD

**Issue by anxcon** [ihsoft/KIS#106]
lets face it, some containers in life are item specific, can only plug a spark plug into that slot of the engine etc, so!

when KIS space is added to a part by some mod adding KIS support, let it choose "only this item can go in the container", maybe i only want 1 hammer and 1 wrench and 1 roll duct tape to fit in my toolbox, not 2 hammers, not an engine

**Comment by ihsoft** [comment]
Could you please give a specific example of a container which usage is limited by the design and not by the intention? In your example with "hummer, wrentch, and tape" it's not a design limitation. Anything that has size and weight similar to a hummer, a wrench or a tape can be stored in this container.

**Comment by anxcon** [comment]
while many cases (real life) would allow "anything" that fits size/weight to go in, many cases don't due to internal structure, such as a briefcase style container with molded foam to hold the items, or my wrench set that has the plastic molded to fit/hold each specific wrench

if you mean more of why use in KSP, i intend to add it to things such as engines, and only allow "ignitor charges" to fit :) or "sample container" to fit in mr scientists case

**Comment by ihsoft** [comment]
I close it in favor of #10 which is far more cute idea. And it covers this request as well.
