### ISSUE TITLE
Moving a docked port causes physics effects

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#107]
When two compatible ports are connected moving any of them to a different place of the vessel may result in physics effect up to collision. This effect is negligible for the tiny ports but on medium and large ports the impact is severe.

Workaround: Detach the port with "X", then attach as needed.

Possible solution: When breaking a link between two ports call `Undock()` instead of `Decouple()`. It may also fix #95.

**Comment by ihsoft** [comment]
Fixed in 1.2.6

**Comment by ihsoft** [comment]
In order to have this issue reproduced the ports must be docked thru the dock sequence (coupling in editor won't work). Another side effect of using `X` on the docked ports is that their state becomes inconsistent: they continue to believe they are docked.

**Comment by pellinor0** [comment]
As a workaround, corrupted ports can be put into an inventory and stacked on top of good ones. This resets their state.
