### ISSUE TITLE
Mass limit is not checked when grabbing from inventory

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#116]
When an overweight item is stored in inventory it can be grabbed and deployed on the ground. Though, it cannot be put back due to mass limit check.

**Comment by karolrybak** [comment]
Seems like it only affects some MKV USI colonization parts. Here's some screenshots illustrating the problem http://imgur.com/a/epxNI

**Comment by ihsoft** [comment]
For the bug to show up the part needs to be heavier than EVA kerbals can handle. E.g. for one kerbal it's one ton. As long as wet mass of the component is less than 1t there is no problems.
