### ISSUE TITLE
EVA duplicates Kerbals

### ISSUE THREAD

**Issue by Apocryphai** [ihsoft/KIS#123]
Whenever I re-enter a vehicle after an EVA the Kerbal gets duplicated, with one copy entering the ship and another one left outside. The outside one cannot be interacted with or removed from Mission Control.

The issue disappears when KIS is uninstalled.

**Comment by ihsoft** [comment]
Do you use KKS or DeadlyReentry mods?

**Comment by Apocryphai** [comment]
Nope, not got either of them installed. I've got over 80 other mods installed though, I'll put a full list together later on today.

**Comment by ihsoft** [comment]
Well, 80 mods is a way to many. Could you, please, try removing them one by one until the problem is gone? This kind of problems is always a mods conflict.

**Comment by Apocryphai** [comment]
With 1.1 running 80+ mods is perfectly stable. Unfortunately I really don't have the time to remove them one by one, restart the game each time and track it down. That would probably take me 3-4 hours. 

Here's my mod list, just close this issue and if anyone else posts that they have the same issue then you've got this list to compare with. Like I said, the issue stopped as soon as I removed KIS.

ModuleManager
AutoAsparagus
BetterBurnTime
BetterCrewAssignment
CapCom
Chatterer
ColorCodedCans
ContractsWindowPlus
DecoupleFromHeatshield
DistantObject
DistantObject-default
DockingPortAlignmentIndicator
DockingPortSoundFX
EngineLighting
EnvironmentalVisualEnhancements
EnvironmentalVisualEnhancements-HR
EVAStruts
EveBiomesPlus
FilterExtensions
FilterExtensionsDefaultConfig
FilterExtensionsStockRework
CommunityTechTree
FuelTanksPlus
GPOSpeedFuelPump
HangarGrid
ImprovedChaseCamera
JoolBiomes
KAS
KerbalEngineerRedux
KerbalJointReinforcement
KerbalNRAP
InfernalRobotics
SmartStage
RasterPropMonitor
ContractRewardModifier
ProgressParser
ContractParser
Kopernicus
InterstellarFuelSwitch-Core
CommunityResourcePack
RasterPropMonitor-Core
KWRocketryRedux
KWRocketryRedux-InstantPwr
LandingHeight
MakeItSmall
MechJeb2
NavballUpDefault
PartAngleDisplay
PartWizard
AmbientLightAdjustment
Toolbar
PlanetShine
PlanetShine-Config-Default
ProceduralFairings
RCSSounds
SCANsat
KSPInterstellarExtended
TweakScale
InterstellarFuelSwitch
GCMonitor
MechJebEmbeddedUniversalCareer
NoMoreGrindRedux
CustomBarnKit
KerbalAlarmClock
ScienceFunding
TriggerAu-Flags
BetterScienceLabsContinued
ConnectedLivingSpace
DMagicOrbitalScience
ExtraPlanetaryLaunchpads
Karbonite
KarbonitePlus
KerbalKrashSystem
TWR1
UniversalStorage
USI-SubPack
KerbalPlanetaryBaseSystems
TextureReplacer
SpacetuxSA
USITools
USI-Core
FirespitterCore
AutomatedScienceSampler
KerboKatzUtilities
AlternatorsForAll
PreciseNode
