### ISSUE TITLE
Yet another EPL interaction problem - container cost calculation

### ISSUE THREAD

**Issue by progfz** [ihsoft/KIS#14]
Extraplanetary launchpads cost for items in containers is calculated in a wrong way and any resource could be made from rocket parts.

Steps to reproduce:
- install KIS and EPL
- make new ship in VAB/SPH
- add KIS container
- put any small tank with fuel into KIS container
- look at EPL cost - there is no optional fuel cost there and rocket parts cost is enormous high
- remove tank from container and add it directly
- look at EPL cost - there is optional fuel cost and rocket parts cost is much smaller

**Comment by KospY** [comment]
New version of EPL is now taking into account container content.
http://forum.kerbalspaceprogram.com/threads/59545-1-0-x-Extraplanetary-Launchpads-v5-1-91-%28beta%29?p=1910903&viewfull=1#post1910903
