### ISSUE TITLE
Can't drop items in seats/containers

### ISSUE THREAD

**Issue by senden9** [ihsoft/KIS#149]
### Description:

Hi,
i can't drop items in seats/containers. Because a picture says more that 1000 words and a video consists of many pictures i uploaded a [screencast](https://github.com/KospY/KIS/files/276326/Screencast_05-22-2016_03.13.25.PM.webm.zip) that shows the issue.
### Data:
- I use a manual downloaded version 1.1.2 of KSP.
- KIS v1.2.9
- OS: Arch Linux
- CPU: Intel(R) Core(TM) i5-4430 CPU
- RAM: 16GB
- GPU: GeForce GTX 650 Ti
### Mods:
- InfernalRobotics
- kRPC
- InfernalRobotics-LegacyParts
- KIS
- KerbalAlarmClock
- KerbalOpticalAlignmentSystem
- KAS
- TweakScale
- RasterPropMonitor
- SCANsat
- DockingPortAlignmentIndicator
- Toolbar
- ContractConfigurator
- ModuleManager
- RasterPropMonitor-Core
- KerbalEngineerRedux

All mods installed though CKAN.

**Comment by ihsoft** [comment]
Could you please give a screenshot in some more common format (jpg, png, etc)? I have no idea what ".webm" is.

**Comment by senden9** [comment]
WebM is a video file format. I think it is relatively common. I have uploaded it to [YouTube](https://youtu.be/FyQrTUmpUQs) because i think a video is better that a screenshot in this case. YouTube reduced the resolution of the video.

**Comment by ihsoft** [comment]
This format is not common on Windows. At least not in Windows 7 or 10 :)

Are you on a laptop? Could you please check debug logs?

**Comment by senden9** [comment]
KSP runs on a PC. I will check/upload the logs when I'm at home again.

**Comment by senden9** [comment]
Here is the [Player.log](https://github.com/KospY/KIS/files/284940/Player.log.txt).

**Comment by ihsoft** [comment]
I don't see any errors in the log. Have you tried to reproduce the issue before grabbing it? Can you drag/drop items if only KIS and KAS installed?

**Comment by senden9** [comment]
Yes. I deleted the log, reproduced the bug and upload the logfile.

I try it with a new KSP installation folder and a new savegame. Here is the new log: [Player.log.txt](https://github.com/KospY/KIS/files/286955/Player.log.txt). The only installed mods are now KIS, KAS and Module Manager. (I doesn't really need this mod but it sound nice. If you have no ideas we can also stop investigation.)

**Comment by ihsoft** [comment]
Still nothing in the log. I see messages saying KIS has loaded but there is nothing related to the items drag-drop. No errors, nothing. It looks as UI just never tried to grab any item.

Try the following. Change field `partGrabModifiers` in `settings.cfg` to value `AnyControl`. Then, reload the game and in the editor try dragging parts with `Ctrl` key pressed.

If it doesn't help then I give up. Looks like a specifics of Linux player. As a last resort try system drivers update and clean resinstall of the game. Or consider running game under `wine`, it may help if the issue is Linux related.

**Comment by senden9** [comment]
Hey, the modification with "partGrabModifiers" helps :)
If you need it, here is another [Player.log.txt](https://github.com/KospY/KIS/files/287207/Player.log.txt). But from me this is solved.

Edit: It also works without this modifications and with the other mods installed. Therefore i clicked on a item, then move the cursor and clicked again. The modwindow doesn't works. But if i click and hold the mousebutton, move the cursor and release the button everything works like expected.

**Comment by ihsoft** [comment]
Good! Looks like drag-n-drop works slightly different in Linux player. Btw, you may bind other shift keys if you don't like `Ctrl`. See details here: https://github.com/KospY/KIS/wiki/Settings.cfg#editor

**Comment by ihsoft** [comment]
> But if i click and hold the mousebutton, move the cursor and release the button everything works like expected.

This is what we call "drag-n-drop". The mod is designed to work this way :)

**Comment by senden9** [comment]
OK. This was some sort of layer 8 problem. But thanks for your time.
