### ISSUE TITLE
"CKAN" Repository 

### ISSUE THREAD

**Issue by morph9833** [ihsoft/KIS#150]
CKAN doesnt detect the new version(1.2.10). The program still shows up the old one (1.2.9), as the latest version of it.
So im unable to update over the mod manager.

Greetings,

**Comment by ihsoft** [comment]
Yeah, they've changed how mods are published on CKAN so, some extra work needs to be done.

See forum's post: http://forum.kerbalspaceprogram.com/index.php?/topic/101928-112-kerbal-inventory-system-kis-129/&do=findComment&comment=2599174

**Comment by ihsoft** [comment]
It's fixed.
