### ISSUE TITLE
Inventory reacts to flag writing.

### ISSUE THREAD

**Issue by Jenerix525** [ihsoft/KIS#152]
If one uses the letter X or numbers in the text entry for flags, they are still picked up as inventory shortcuts.
Numbers can be worked around, as the numpad doesn't have the issue.
X seems unavoidable, but is less problematic, especially if the held item is un-equipped beforehand.

Presumably, this would apply to any text entry while on EVA.

**Comment by ihsoft** [comment]
Yeah. Whole game is designed so what UI controls and parts are intermixed. I'll take a look to see if/how such situations can be detected.
