### ISSUE TITLE
Cannot deatch broken solar panel

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#160]
See details: http://forum.kerbalspaceprogram.com/index.php?/topic/101928-112-kerbal-inventory-system-kis-1211/&do=findComment&comment=2632531

**Comment by henrybauer** [comment]
If I remember right, this is because broken solar panels don't have a collider, so there's nothing to grab.

**Comment by ihsoft** [comment]
Indeed, the stock part doesn't provide collider for a broken panel. In order to fix it KIS needs to create a collider by itself. Though, better approach would be adding collider by Squad team.

**Comment by ihsoft** [comment]
Created a [bug](http://bugs.kerbalspaceprogram.com/issues/13338) for Squad team.

**Comment by ihsoft** [comment]
Still no progress on the Squad's side :(

**Comment by ihsoft** [comment]
Since Squad team doesn't want do handle it, I'm going to handle it in KIS. After all, breaking the solar panels is a thing that happens.
