### ISSUE TITLE
KSP 1.1.3: Missing method exception

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#161]
When scene object is attempted to be moved via KIS the following error is thrown:

```
160621T214418.065 [EXCEPTION] [KIS.KISAddonPickup.OnPointerAction] MissingMethodException: Method not found: 'Vessel.SetPosition'.
   at KIS.KISAddonPickup.OnPointerAction (PointerTarget pointerTarget, Vector3 pos, Quaternion rot, .Part tgtPart, System.String srcAttachNodeID, .AttachNode tgtAttachNode)
   at KIS.KISAddonPointer.UpdatePointer ()
   at KIS.KISAddonPointer.Update ()
```

WORKAROUND. Drag the part from scene into inventory. Then drag it out of inventory to the new location.

**Comment by ihsoft** [comment]
No actual code change needed. Only rebuild with the latest KSP binaries.

**Comment by lesbianlizard** [comment]
- KSP 1.1.2
- KIS 1.2.12 from CKAN
- Arch Linux x86_64

```
[LOG 23:00:29.680] Set pointer mode to: Drop
[EXC 23:00:30.132] MissingMethodException: Method not found: 'Vessel.SetPosition'.
        KIS.KISAddonPickup.OnPointerAction (PointerTarget pointerTarget, Vector3 pos, Quaternion rot, .Part tgtPart, System.String srcAttachNodeID, .AttachNode tgtAttachNode)
        KIS.KISAddonPointer.UpdatePointer ()
        KIS.KISAddonPointer.Update ()
[LOG 23:00:30.612] Launcher here(in write): False
[LOG 23:00:30.810] Cancel key pressed, stop eva attach mode
[LOG 23:00:30.810] StopPointer()

```

I'm getting this error when trying to place/move parts with 1.1.2. It does not occur with 1.1.3.

**Comment by ihsoft** [comment]
KIS 1.2.12 is _incompatible_ with 1.1.2. It will only work with 1.1.3 and higher.

And thanks for the bug, I'll add minimum version requirement into CKAN file.

**Comment by lesbianlizard** [comment]
Ah ok, glad to help.

In that case, where can I download the last 1.1.2-compatible release?

Edit: here: http://kerbal.curseforge.com/projects/kerbal-inventory-system-kis/files
