### ISSUE TITLE
Some nodes unusable after detaching part

### ISSUE THREAD

**Issue by drewcassidy** [ihsoft/KIS#164]
Sometimes when I detach a stack-attached part from my shuttle, Im unable to use that node to attach with. Cycling with `r` doesnt even show the node I want. The only solution is to put the part in a container, which is impossible for some larger parts. So far this has happened with the MKS inline greenhouse and a custom welded part I made. It's not completely consistent. Nothing appears in the logs at all

edit: quickloading fixed the issue with my welded beam, but not the greenhouse. This may be two separate bugs

**Comment by ihsoft** [comment]
Check the logs next time your recently detached part has the issue. Usually such things happen when there was an error or exception in the middle of the process. Part's state is always inconsistent when it happens, and unavailable node is not the worst scenario. MKS is known to have issues with KIS.

**Comment by drewcassidy** [comment]
Here is the log from the start of the EVA: https://gist.github.com/drewcassidy/0053455b23d9a0fcbdd297e22b910449

Also i was mistaken, the greenhouse is from USI life support, not MKS. Im fairly certain your incompatabilities with MKS are due to its inflation, which this doesnt do

The ghosted node also cannot be attached to. hovering over where it should be with another stack attach part just shows surface attach

**Comment by drewcassidy** [comment]
A workaround is to detach the part so its freefloating, then quick save and load again, in case anyone else encounters this problem before it is fixed

**Comment by drewcassidy** [comment]
I found the problem with the greenhouse, it has 2 nodes with the same name. I opened a pull request for USI-LS [here](https://github.com/BobPalmer/USI-LS/pull/124). You may still want to check for nodes that have the same name though

**Comment by ihsoft** [comment]
Great! Thank's for taking care of it.

As for the node names checking I don't think it's worth it. Part misconfiguration is a problem of the part, and handling it in KIS will increase code complexity for nothing.
