### ISSUE TITLE
EVA items not listed in edditor

### ISSUE THREAD

**Issue by WeirdoWithACello** [ihsoft/KIS#169]
[https://65.media.tumblr.com/ba39c0e887203e07666c9996692950e7/tumblr_obrsvhtEPa1us7rh4o1_1280.png](url)

In the editor, there are no items visible in the EVA tab. The files are all present and accounted for, just not listed.

For the sake of UbioZur's wleding-mod, I've reloaded the database multiple times. That's the only cause I can think of, though I'm open to any and all suggestions.

**Comment by ihsoft** [comment]
Please, attach KSP.log file.

**Comment by WeirdoWithACello** [comment]
Where would I find it?

**Comment by ihsoft** [comment]
In the game's root folder.

**Comment by WeirdoWithACello** [comment]
[log.txt](https://github.com/KospY/KIS/files/414584/log.txt)

**Comment by ihsoft** [comment]
As far as I can tell from the log the KIS code worked as expected. There are only two options I may guess: improper setup of KIS or a mods conflic issue. Try clean re-install of KIS mod (i.e. deleting whole KIS folder, and installing from a fresh archive). If it doesn't help try removing all the mods but KIS, and check if the items show up.
