### ISSUE TITLE
Portable Struts aren't stackable

### ISSUE THREAD

**Issue by dmarcuse** [ihsoft/KIS#171]
Not sure whether this is due to KAS or KIS, but the CS-R2 Portable Struts don't have an option to set the amount in a KIS inventory like the fuel ports do, meaning you need one slot for each strut endpoint (wasting a lot of volume)

**Comment by ihsoft** [comment]
It's a known mods compatibility issue. Some mods add extra modules to the existing parts, and KIS only allows stacking if _all_ the modules on the part are known to KIS. The stackable modules/parts are whitelisted via [settings.cfg](https://github.com/KospY/KIS/wiki/Settings.cfg#stackablemodule). To fix the issue in your game you need to find which mod introduces the problem, and then figure out the modules it adds.

**Comment by dmarcuse** [comment]
Hmm, alright thanks.
