### ISSUE TITLE
EVA kerbals not moving properly on the Mun.

### ISSUE THREAD

**Issue by Niko18** [ihsoft/KIS#172]
EVAs act strangely on the Mun. They seem to be walking with their running animation and they are not able to run at all. No issues with the jetpack. This happens even when the kerbal's inventory is empty. Other mods I have are KAS and Trajectories.

**Comment by ihsoft** [comment]
Can you reproduce it without other mods? It's OK when kerbal cannot run with stuff in the backpack (due to heavy mass), but it's expected to work with an empty backpack.

By a chance, can you make and share a video?
