### ISSUE TITLE
[KSP 1.2] EVA cnaister stopped working

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#175]
http://forum.kerbalspaceprogram.com/index.php?/topic/149848-12-kerbal-inventory-system-kis-v130/&do=findComment&comment=2801289

**Comment by ghost** [comment]
Here's the logs, and a quicksave in case that's useful.
I just hacked gravity, went on EVA and used up some fuel, and then tried to refuel with the canister.
After trying to refuel a few times, I alt-F4'd.

Hopefully someone will be able to extract useful info out of the logs. Everything looked pretty uneventful in there to me.

[KSP.log.txt](https://github.com/KospY/KIS/files/526814/KSP.log.txt)
[Player.log.txt](https://github.com/KospY/KIS/files/526834/Player.log.txt)
[quicksave.sfs.txt](https://github.com/KospY/KIS/files/526815/quicksave.sfs.txt)

**Comment by Netrilix** [comment]
I'm experiencing the same bug. I wanted to test the EVA-11 before I brought it into space, so I stood on the launchpad and burned up all my EVA fuel. I then tried everything I could think of to refuel my Kerbal from the EVA-11 in his inventory, and I couldn't find any way to make it work. I haven't tried it in space, this was my first time trying to use one.

**Comment by SPS6** [comment]
Same, confirming issue, I didn't see anything print to the log.
