### ISSUE TITLE
Tool Parts (wrench, drill, ext) not showing up on parts list

### ISSUE THREAD

**Issue by TeflonDon262** [ihsoft/KIS#177]
I went as far as only installing KIS and KAS to test this but even with only those mods installed the tools aren't showing up at all in the part list.  I do still get the containers and other parts but no tools for construction
[output_log.txt](https://github.com/KospY/KIS/files/546433/output_log.txt)

**Comment by ihsoft** [comment]
How did you install the mods? Please, provide `KSP.log`.

**Comment by TeflonDon262** [comment]
I got the newest release of it again, installed it, parts still missing but then i deleted all other mods and they showed up.  I installed it per normal mod install, KIS and KAS were placed in the gamedata folder.  It had to be another mod causing the issue because like I said once I deleted the mods the parts showed up,  still not sure what mod caused the issue because I eventually installed all the mods back and there no issue anymore.  Sry for the waste of time but I just couldn't figure it out,  I've used your mods since before 1.0 and I think they are essential parts for KSP.  Thanks for the hard work and I'll post a ksp.log if the problem comes back from a possible mod conflict

**Comment by jonl2** [comment]
I have a similar problem, but KSP is stuck forever loading KIS/Parts/wrench/part/KIS_wrench .
I cant load the game because it keeps breaking (ie. stops loading) at this point, although I can close the game and etc. Anybody know whats going on?

**Comment by ihsoft** [comment]
We need KSP.log file to investigate. It most likely is a mod conflict issue.
