### ISSUE TITLE
Full mass used for empty parts for purpose of removing from containers.

### ISSUE THREAD

**Issue by bwucke** [ihsoft/KIS#178]
Example: Rockomax X200-8 tank, empty, mass 0.5t. 
The kerbal is able to detach and lift it without problem.
http://i.imgur.com/jZbBMok.png

Upon depositing the tank inside the container, the kerbal is unable to remove it. "Too heavy. Bring more kerbal [4.500t > 0.500t ]"
http://i.imgur.com/7QLbMr6.png

This makes building rockets "from scratch" with OSE workshop really hard. It's a different thing to remove a 4-ton orange tank using 4-5 kerbals, then fill it, than to try to handle the "full" 36 tons, despite it it being empty.

**Comment by ihsoft** [comment]
I was able to reproduce the bug.

Out of curiosity, how did you manage to put the tank into 6K container? The parts has volume of 6,600 liters and the container offers only 6,000.

**Comment by bwucke** [comment]
It shows up as 422.34l for me (see the second screenshot). I'm not sure, but OSE Workshop might be at fault, or maybe old version of KIS where I was preparing the screenshots with bug demo (not my primary computer). Sometimes the volumes presented are also weird.
