### ISSUE TITLE
Compatibility issue with RCS Build Aid

### ISSUE THREAD

**Issue by JeffreyCor** [ihsoft/KIS#19]
When RCS Build Aid is installed along with KIS, vessels saves with a part in a KIS inventory slot will not load properly. Screenshots and log included to aid in finding the issue.

Built ship and added part to KIT inventory
https://www.dropbox.com/s/5i04qb7ut0...shot3.png?dl=0

Saved and loaded after adding part, this is result
https://www.dropbox.com/s/zi9sdrjj9v...shot4.png?dl=0

Log to hopefully indicate what is going on
https://www.dropbox.com/s/tk8zfv36u9...t_log.txt?dl=0

**Comment by JeffreyCor** [comment]
Update to this, a new version of RCS Build Aid is available and this new version no longer seems to have the compatibility issue.

**Comment by KospY** [comment]
Thank you for the information, I close the issue.
