### ISSUE TITLE
Set decouple momentum on Cargo Mount to zero

### ISSUE THREAD

**Issue by wile1411** [ihsoft/KIS#200]
Currently the "Release" menu option lets the cargo go with some force. 

Enhancement request - A tweakable would allow this to be set to zero / percentage value seeing as it's using the decouple command.

Reason - lighter containers are currently sent flying away

**Comment by ihsoft** [comment]
In fact the mount applies no force on decouple. It's a collider on the container that gives momentum.

**Comment by wile1411** [comment]
Ah, I was hoping it would be an easy fix. I would be nice, but all fine if you want to close this as too low a priority.

**Comment by enceos** [comment]
@wile1411 I fixed the collider, thanks for the report.
