### ISSUE TITLE
Inventory Context Menu on EVA Kerbal (bill) not showing

### ISSUE THREAD

**Issue by rikwilbrink** [ihsoft/KIS#210]
Got a MK1 Pod
Loaded it up with wrench, 2 solar panels and a battery.
Launch, Orbit
Bill EVA
RightClick Bill. 
=> No Context menu: Inventory.
RightClick Pod. (bill still eva)
=> No Context menu: Inventory.

![ksp2](https://cloud.githubusercontent.com/assets/1725967/25254135/52de7fb2-2624-11e7-8fa5-cb7ca7d1a640.png)

Bill Boards Pod again.
Rightclick Pod.
=> Bill's inventory:
[MK1 Pod avatar with wrench, 2 solar panels and a battery.]

![ksp1](https://cloud.githubusercontent.com/assets/1725967/25254131/485da70c-2624-11e7-88e8-2dd3e048ff36.png)

I get the feeling that the context menu is not added to the EVA Kerbal, but it is added to the pod.

**Comment by ihsoft** [comment]
It's expected to not have context menu for the empty pod: no crew, no inventory. However, it's not normal to not have the inventory button on the EVA kerbal. I have two quick suggestions:

* Somehow the ModuleManger in you game has failed to apply the inventory module to the kerbals. Try checking if you have the latest MM version installed.
* There is a mods conflict. Try removing all the other mods and see if problem still exists. You can leave KER and KAC, they are known to not interfere with KIS.

How many other mods do you have in the game? I could try debugging the save file. My setup does have KAC and KER.

**Comment by rikwilbrink** [comment]
Grabbed the ModuleManager dll from the source/Deps from your git, and that did the trick. Somehow it didn't get installed while adding mods.

Thanks for the quick response!

Now i can finally attach some solar panels and a battery to the stranded probe. It's supposed to ferry 2 tourist around, but it ran out of power.

**Comment by ihsoft** [comment]
You're welcome.

Out of curiosity, how did you install KIS initially? The package on Curse does have MM in the archive, and CKAN should have installed it by the dependency requirement.

**Comment by rikwilbrink** [comment]
I downloaded a bunch of mods from curse with a fresh install.
And mass extracted the zips. But since not all mods consider unpacking in
the gamedata the correct location, I got a whole mess of folders. So I
deleted all, except for squad.
Then 1 by 1 dragged the folder from the zip.
For kis, I probably overlooked MM.

**Comment by ihsoft** [comment]
Ah, that explains how it get missed. Consider using CKAN, it solves this kind of issues.
