### ISSUE TITLE
After update to 1.5.0 KSP does crash

### ISSUE THREAD

**Issue by alrabe** [ihsoft/KIS#213]
KIS 1.4.4 works fine
the only mode not in the CKAN file is "Fog of Tech"
[crash.ckan.txt](https://github.com/ihsoft/KIS/files/1033642/crash.ckan.txt)

**Comment by ihsoft** [comment]
According to the logs you have many other mods. Any of them can be the
issue. The latest KIS version is known to NOT crash under 1.3. Please, try
using KIS alone to confirm it's the problem.

сб, 27 мая 2017 г., 9:12 Al Bex <notifications@github.com>:

**Comment by GerkinDev** [comment]
Same here, maybe it is an incompatibility between 2 mods. Anyway, I updated to KIS 1.5.0: game crashed. I forced downgrade to 1.4.4 with exact same mod list & game config and it worked well.
[output_log.txt](https://github.com/ihsoft/KIS/files/1034303/output_log.txt)
[error.log.txt](https://github.com/ihsoft/KIS/files/1034304/error.log.txt)

**Comment by alrabe** [comment]
I still have 1.2.2 running here. Maybe that's the point. 

Edit: I checked now KIS 1.5 with KSP 1.2.2 and no other mods. No problems - so it looks like an incompatibility with another mod.

**Comment by ihsoft** [comment]
I'm pretty sure it's not an incompatibility issue. It's just another mod that crashes the game.
