### ISSUE TITLE
Not able to access inventory of Kerbals or Containers from EVA

### ISSUE THREAD

**Issue by mjt2000d** [ihsoft/KIS#214]
Once in EVA, the ability to access Kerbals inventory is not available, and containers do not open their inventory even though the button is pressed.

**Comment by ihsoft** [comment]
Please, double check if you have a correct version of `ModuleManager` installed in your game. For KSP 1.3. the minimum working version of MM is 1.8.0.

**Comment by mjt2000d** [comment]
CKAN was used to download it, ModuleManager is at version 2.8.0

**Comment by ihsoft** [comment]
Yes, I meant 2.8.0 of course. Well, let's see at your logs then. I need `KSP.log` file from the game's root.

**Comment by mjt2000d** [comment]
What file would that be in?

**Comment by ihsoft** [comment]
It's located in the folder where the game is installed. Do you know where is your game installed? If not you may know it from Steam: right click on the game in the browser, choose "Properties", then choose "Browse local files..." in the opened dialog.

**Comment by mjt2000d** [comment]
I know where are the folder for the overall game is, I just don't know where the file you want is. Like what folder under Kerbal Space Program.

**Comment by ihsoft** [comment]
The "overall" folder is the "game's root" :) This is where the file is located. If you still cannot find it, try doing the file search by the name.

I need the log, captured right after you've reproduced the issue. So run the game, reproduce the issue, close the game, capture the file.

**Comment by mjt2000d** [comment]
I've searched for the individual file and the folder and neither show up on the search.

**Comment by mjt2000d** [comment]
Do you mean the output_log? That is the only thing I can find that is similar to what you are talking about.

**Comment by ihsoft** [comment]
No, `output_log` is different, it's located in `KSP_Data`/`KSP_x64_Data` folders. This file is useless for the mods problems troubleshooting. The one I need lives in the folder one level up. Try finding `KSP.exe` file, the `KSP.log` will be right there, in the same folder.

**Comment by mjt2000d** [comment]
The folder above KSP_Data and KSP_x64_Data is Internals and there is nothing in it

**Comment by ihsoft** [comment]
Did you find `KSP.exe`?

**Comment by ihsoft** [comment]
And by saying "one level up" I meant *level in the folders hierarchy*, not the actual line on the screen (how is that a "level"?). I.e. unless you have own custom set up, your game is located in a steam folder like this:
```
D:\Steam\steamapps\common\Kerbal Space Program\
```

The drive letter can be different.

**Comment by mjt2000d** [comment]
My game is in that setup, but there was nothing in that top level so I thought you meant next folder. I have seen KSP.exe while doing things before, but I could not find it again. Is it supposed to be in the Kerbal Space Program folder and nothing lower? Because it isn't

**Comment by ihsoft** [comment]
I cannot imagine a valid setup where `KSP.exe` is not located in this folder. Just in case try doing files validation via Steam. And keep in mind that the log file is created during the game launch, so if you see the `KSP.exe` file but not the `KSP.log` then you just need to run the game. Don't forget to exit the game before capturing the log file.

**Comment by mjt2000d** [comment]
![kerbal file pic](https://user-images.githubusercontent.com/29508702/27450108-9766fe38-5758-11e7-9636-3f7db3487914.JPG)

**Comment by ihsoft** [comment]
I see the file. Your explorer view doesn't show the known file extensions, that's why you don't see exactly `KSP.log`. In the explorer go into the menu "View", and select "Show file extensions".

FYI. The log file is that "KSP" that has a text file icon.

**Comment by mjt2000d** [comment]
Oh okay, that makes sense. It won't let me attach the file, says its not compatible and a straight copy of the text has too many characters.

**Comment by ihsoft** [comment]
Put the file one some free file sharing services. E.g. on the Google Drive. Then just post a link here.

**Comment by mjt2000d** [comment]
[https://1drv.ms/u/s!As12WL0Pbux1iy_7VQLCm3kBb08i](url)

**Comment by ihsoft** [comment]
According to the logs, there is no `ModuleManager` in your system. Please, provide a screenshot of the folder's content for `D:\Steam\steamapps\common\Kerbal Space Program\GameData\`.

**Comment by mjt2000d** [comment]
Module Manager does not show up, but CKAN says it has been installed

**Comment by ihsoft** [comment]
Well, for KIS to work the `ModuleManager` must be *actually* installed. It doesn't matter what CKAN does say. If there is no manager in your system, but CKAN says there is one, then it's a question for the CKAN developers. I cannot speak for them.

As a workaround try removing the manager from CKAN. Then, add it back and check the game's directory.

**Comment by ihsoft** [comment]
@mjt2000d, I assume this issue is resolved. Feel free to reopen it if after the proper installation of the `ModuleManager` you still have the problem.
