### ISSUE TITLE
Parts are attached offset when Kerbals are moving

### ISSUE THREAD

**Issue by drewcassidy** [ihsoft/KIS#216]
When attacking parts, they appear to be placed slightly offset in the direction a kerbal is moving. it appears you are adding the part one frame after the click but relative to the kerbal, not the subject of the attachment

**Comment by ihsoft** [comment]
Initially, the part is created in the kerbal's local space, and the part is not immediately attached (it needs to get initialized). So your suggestion is correct. However, before doing the actual attach, the part is aligned against the target. I would agree there can be an edge case when this alignment doesn't work. Can you reliably reproduce this issue? Can you make a short video to demonstrate it?

**Comment by drewcassidy** [comment]
Sure, I’ll make a video of it in the morning. it happens 100% of the time when attaching things while the kerbal is moving relative to the ship. its especially apparent when stack mounting two identical parts and while moving quickly

**Comment by ihsoft** [comment]
This issue is likely fixed by #217. Feel free to re-open if you are able to reproduce it.

**Comment by drewcassidy** [comment]
this appears to still be the case. it also might be amplified by using rescale mods, similar to the stock shrouds bug

**Comment by ihsoft** [comment]
Can you reproduce it on the launchpad using any stock part affected with a rescale mod? The compatibility issues are known to happen when another mod mangles with the part's scale. I can try to achieve a compatibility (if at all possible), but I need a simple and reliable reproducible case.

**Comment by drewcassidy** [comment]
yup I'll work on some steps to accurately reproduce it. when I say rescale mod I mean rescales the solar system, not the parts
