### ISSUE TITLE
[Feature] Containers should be KAS compatible

### ISSUE THREAD

**Issue by DoctorFoo** [ihsoft/KIS#22]
As of right now, it's impossible to "carry" a container from one mount to another when they're a distance apart. Utilizing KAS would make it much easier to carry while in EVA a container from one spot (or one ship) to another.

**Comment by KospY** [comment]
I played a little bit more about container manipulation in space and I must admit that I have changed my mind about this...
I think the planned eva tether for container manipulation in 0g will be a nightmare to use, as it will unbalance the eva RCS, and cause container to spin around without control. In fact, it will be more easy to move containers if they are attached to the kerbal (like KAS). As container mass is addded to the kerbal, there is no problem about this afterall, moving heavy containers will realistically be more difficult and use more RCS fuel, and moving multiple containers once will always need some kind of vehicule.

However, I'm worried about carrying container on the ground. For me it seem like a "cheat", as you can carry 1000L on back without any downsides (like a giant backpack). 
First I thought I would disable this feature when kerbal is on the ground, but after some thinking the current system is not really practical for some tasks like attaching container on top of a rocket (using ladders). 
So what I planned to do is to disable running (or restrict kerbal speed) when a container is carried. This way there will be no problem, and rovers will also always be usefull for moving containers on long distance. 
What do you think ?

**Comment by DoctorFoo** [comment]
I think restricting the speed would work best. It's conceivable they'd be able to move them to some degree on the ground anyhow (like with the KAS containers).

**Comment by metl** [comment]
On this same line, and I know this may be a stretch, but is there any way to re-balance the kerbal once an item is on their back? controlling a kerbal in 0g is extremely difficult when even holding something as small as a strut end point. Why do thins seem to so strongly affect eva controllability? It is doable, but going from one side of a station to the far other end can be extremely tedious and frustrating. (i.e "not fun")

**Comment by KospY** [comment]
Carriable containers added in 1.1
