### ISSUE TITLE
Kerbals can't store more than 1L

### ISSUE THREAD

**Issue by Nomeo** [ihsoft/KIS#229]
For some weird reason my kerbal can't store more than 1L, this bug happened to me a lot of times, I've
 tried to relaunch the game, reinstall, checked the Settings and everything is correct and fine, but for some reason, i can't store more than 1L in my inventory, Please help!! 

EVA Inventory in settings CFG says:

EvaInventory
	{
		inventoryKey = tab
		rightHandKey = x
		helmetKey = j
		slotsX = 2
		slotsY = 4
		slotSize = 50
		itemIconResolution = 128
		selfIconResolution = 128
		maxVolume = 300
		openSndPath = KIS/Sounds/inventoryOpen
		closeSndPath = KIS/Sounds/inventoryClose

and I still have the max volume of 1
here's a screenshot:

![kerbal space program 10_28_2017 1_10_51 pm](https://user-images.githubusercontent.com/33175356/32133500-b7391fa0-bbe1-11e7-8087-b8b158e16dff.png)

**Comment by ihsoft** [comment]
Did you try [the troubleshooting steps](https://github.com/ihsoft/KIS/wiki/Troubleshooting#a-capsule-seat-inventory-can-only-have-1l-of-stuff-in-the-editor)?

**Comment by Nomeo** [comment]
Yes i've tried , Forgot the logs
[KSP.log](https://github.com/ihsoft/KIS/files/1424157/KSP.log)
btw the game is still running

@ihsoft

**Comment by ihsoft** [comment]
You've installed KIS into a wrong location: `GameData\Kerbal Inventory System v1.7\KIS\Plugins\KIS.dll`. It will not work this way. Please, read [this topic of the guide](https://github.com/ihsoft/KIS/wiki/Troubleshooting#extracting-the-release-archive-into-a-wrong-location).

**Comment by Nomeo** [comment]
Ah , i renamed the KIS File to Kerbal Inventory System v1.7 so i can see the ver , maybe that's the problem , gonna try that

**Comment by ihsoft** [comment]
I assume this bug is resolved. Feel free to reopen it if not.
