### ISSUE TITLE
Missing Seat-Inventory after spawn on Launchpad

### ISSUE THREAD

**Issue by hraban35** [ihsoft/KIS#256]
All added Parts inSeatInventory where lost by spawn at the Launchpad.

**Comment by ihsoft** [comment]
Where these seats occupied by kerbals?

**Comment by hraban35** [comment]
Ok, seats occupied by Kerbals will keep the assigned inventory until the next time the game is loaded.
After that, the seats are empty, though occupied with Kerbals.
If a kerbal wears one of the expansion vintage suits, the same applies but the equip function does not work.

**Comment by ihsoft** [comment]
Could you please make and share a short video? Also, double check that you use the latest KIS version (1.11), the game is KSP 1.4, and the MM mod is of compatible version.

**Comment by ihsoft** [comment]
The vintage suites issues was addressed in #248. Other than that, I cannot see any problem. Please, re-open this use if you have more info (logs, screenshots, etc.).
