### ISSUE TITLE
inventory item when spawning

### ISSUE THREAD

**Issue by JebEddun** [ihsoft/KIS#260]
Not really sure of this is right place to ask so sorry in advance if it is.

When spawning a kerbal, is it possible or could you make it possible to have an option to have items in the inventory of a spawned kerbal. (Using contract configurator to spawn)

**Comment by ihsoft** [comment]
Doesn't look as a simple thing to implement. What's the use case?

**Comment by JebEddun** [comment]
I guess I found a way around my problem. I wanted to spawn a kerbal in a Bear Grills type survival situation with just Kis items and I figured out that by simply spawning a vessel with the kerb in it would let me add the KIS module to it i guess. I'll just spawn a .craft file that has something i added in inventory. I do that a lot. ask questions and then figure out the answer while waiting. Sorry and thanks 🗡
