### ISSUE TITLE
Ghetto blaster and Guitar dont work

### ISSUE THREAD

**Issue by 678GUY** [ihsoft/KIS#266]
When you press play on both of these items nothing happens, it dosent matter if its in the kerbels hand or on the ground

**Comment by ihsoft** [comment]
Could you please provide the logs?

**Comment by 678GUY** [comment]
https://file.io/Om4bSM

**Comment by ihsoft** [comment]
It gives me 404.

**Comment by 678GUY** [comment]
weird. try this
https://ufile.io/m5srt

**Comment by ihsoft** [comment]
Please, provide the other log: https://github.com/ihsoft/KIS/wiki/Troubleshooting#how-to-get-the-games-log-file

**Comment by 678GUY** [comment]
im so soory for the late reply
http://www.filedropper.com/ksp_2
but here is the log

**Comment by ihsoft** [comment]
You've installed the fun part into an incorrect folder. For this reason the sound paths cannot be found:
```
[LOG 22:23:48.909] Load(Audio): KIS.fun_parts_pack/fun_ghettoblaster/ghettoBlaster1
[LOG 22:23:49.117] Load(Audio): KIS.fun_parts_pack/fun_guitar/guitar
```
For the proper work, the fun parts must live in the following folders:
```
KIS/Parts.fun/fun_basketball
KIS/Parts.fun/fun_beer
KIS/Parts.fun/fun_ghettoblaster
KIS/Parts.fun/fun_golfclub
KIS/Parts.fun/fun_guitar
KIS/Parts.fun/fun_taco
```
