### ISSUE TITLE
KSP 1.5: Equip items and remove helmet actions don't work

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#269]
The kerbal model related actions are not working or the standard suit of the female model.

**Comment by JacobRoth** [comment]
Happening here too. When I have a female engineer try to equip an electric screwdriver I get this error in the console:

`
[LOG 19:39:21.604] Equip item E-SD80 Electric Screwdriver in mode Model
[ERR 19:39:21.604] evaTransform not found !`
