### ISSUE TITLE
ModuleKISInventory compatibility with ModulePartVariants

### ISSUE THREAD

**Issue by omega482** [ihsoft/KIS#277]
Currently, a storage part with multiple meshes (therefore multiple volume options) can only use a single maxVolume and slotsX/slotsY.

**Comment by Kerbas-ad-astra** [comment]
My understanding is that that's a limitation of the stock game -- ModulePartVariants can only change a handful of variables (mass, cost, and node positions, if I understand correctly).

**Comment by ihsoft** [comment]
See #273
