### ISSUE TITLE
cfg file format: Get rid of "equipBoneName" 

### ISSUE THREAD

**Issue by GER-Space** [ihsoft/KIS#279]
and just use the "equipSlot" as the sole type of reference. 

Make a simple Dictionary<string,string> and fill the bone names to the correspnding slot name. This should be easier to use. 
You created the aliases for the bones, but why not just use the "equipSlot" to select the right bone alias?

**Comment by ihsoft** [comment]
"equipSlot" is an arbitrary string. It's not typed and only used to keep some consistency on the model (e.g. not equipping two items on the same arm). It's technically possible to have different slots on the same bone, and vice versa. And what if someone decides to create own slot?
