### ISSUE TITLE
Right click quantity menu should not appear for objects you can't increase in quantity.

### ISSUE THREAD

**Issue by TomFyuri** [ihsoft/KIS#28]
Right click quantity menu should not appear for objects that are impossible to increase in quantity (for example wrench). It's a bit unintuitive.

**Comment by skalou** [comment]
hello, right
 the + and - buttons doesnt work for me exept for explosives, 
or what is "addable"?

**Comment by TomFyuri** [comment]
Hey.
In VAB since latest update, I can't find a single object that is possible to increase in quantity using right click menu. (I admit I didn't search for more than 10 minutes though)

**Comment by KospY** [comment]
Menu has been disabled in KIS 1.1 for parts not stackable
