### ISSUE TITLE
Use the stock functionality to remove helmets from KIS code and properly support the custom helmets

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#281]
It's now a stock game feature.

**Comment by theonegalen** [comment]
I wonder how difficult it would be to have a single button that removes both the helmet and the ring, since you seem to have to write move them separately in the stock implementation.

**Comment by ihsoft** [comment]
In fact, I decided to keep the functionality. It doesn't hurt anyways and people got used to it. However, now it's fully compatible with the stock game. As a nice feature, the KIS hotkey "J" removes both the helmet and the neck ring, while the game's hotkey only removes the helmet. The support for the custom helmets is still working in KIS.

See details and demo video on [Patreon](https://www.patreon.com/posts/23630483).

**Comment by theonegalen** [comment]
Would it be possible to have a function that checks for an atmosphere upon going Eva, which then removes the backpack parachute if the body is airless?
