### ISSUE TITLE
Request: Allow other mods to add partModules to the Stackable list

### ISSUE THREAD

**Issue by SirDiazo** [ihsoft/KIS#31]
As the author of several utility mods, I add partModules to other parts in the game, including one which adds its partModule to every part in the game.

As my partModule is not in the StackableModules list in the Settings.cfg, this results in no part in the game being stackable.

Could you establish a method that would allow other mod makers to add their partModules to the stackables list please?

While you can set things up as you wish, my suggested method would be to load your settings file as a configNode, that allows other mod makers to use a ModuleManager file to add their modules to the stackables list.

I do so here in AGX if you want a reference: https://github.com/SirDiazo/AGExt/blob/master/AGExt/CommonMethods.cs#L58

**Comment by KospY** [comment]
Thanks for the reference. I made the desired changes for KIS 1.1
