### ISSUE TITLE
Stock Parts not stacking in 1.6.1 with no other mods

### ISSUE THREAD

**Issue by jasonttech** [ihsoft/KIS#317]
I noticed that only KIS parts were stacking in my main game. I made a fresh 1.6.1 install and added only KIS 1.18, no other mods Reproduction steps below.
1. Start a sandbox game.
1. Go to the SPH
1. Add a Mk3 command pod and a large Mk3 container.
1. Open the containers inventory.
1. put a cubic strut in the container
1. I also tried RCS, ant engine and a bunch on other parts, The only ones that would stack were the KIS parts.

This problem does not exist on 1.6.1  with KIS 1.16 

This problem exists on 1.17
I also tried switching ModuleManager version between 3 and 4 and that had no effect.

I did not see any errors or hints of what might be wrong in KSP.log or output_log but I have attached the output_log below

[output_log-KIS.txt](https://github.com/ihsoft/KIS/files/2870966/output_log-KIS.txt)

Thank you for your work on this awesome mod!

**Comment by ihsoft** [comment]
Could you please also add KIS.log?

**Comment by jasonttech** [comment]
Where would I find that? I don't see it in the KSP directory or the appdata one that it puts output_log and crash reports.

**Comment by ihsoft** [comment]
https://github.com/ihsoft/KIS/wiki/Troubleshooting#how-to-get-the-games-log-file

**Comment by jasonttech** [comment]
I found some more weirdness with this. I tried adding strutCube to StackableItemOverride.
In the SPH it did not allow me to stack so I added 2 in separate slots. After launching it showed the 1x next to it and I was able to stack, I then reverted to SPH and it allowed me to stack and showed the 1x. I launched again and then tried splitting and it keeps the 1x for the on that started in there but the one that's split off does not show it. I can stack if I drag the non stackable onto the stackable, but if I drag the  stackable onto the non stackable it does not work. This only affects items with the override, items without it are not stackable at all. 

I also realized you probably meant KSP.log both logs are below after doing this. 

![image](https://user-images.githubusercontent.com/43303652/52888906-84b0d380-314b-11e9-9795-f0b0ea6ea27e.png)

[output_log.txt](https://github.com/ihsoft/KIS/files/2871160/output_log.txt)

[KSP.log](https://github.com/ihsoft/KIS/files/2871161/KSP.log)

Edit: In case it matters for reproducing this I am on Windows 10 with 64 bit KSP.

**Comment by ihsoft** [comment]
The inconsistent behavior of the override can be caused by the saved info in the inventory. Need to check it.

As for the issue itself, the logs don't give an answer. Could you, please, attach the save file as well?

**Comment by jasonttech** [comment]
Here's the last save. There's not much in it because I've started with a fresh save each time I test. I'm guessing you're not having this issue so I'm curious what could affect it since I get it from a clean install with no other mods. I also just tested on another computer and it is reproducible there. 

I notice that the way you check if it is stackable in KIS_Item.cs changed a lot. The fact that the override mostly works and the KIS parts work make me think the problem if either here https://github.com/ihsoft/KIS/blob/3bbcc577ebb76b795cbcb22a632eecaa1cc38554/Source/KIS_Item.cs#L358-L359 or on the config loading/parsing,


Again, thank you for your help with this!

[save.zip](https://github.com/ihsoft/KIS/files/2871558/save.zip)

**Comment by ihsoft** [comment]
Yeah, I was able to reproduce. Looks like game had new modules, that `KIS` is not aware of.

**Comment by jasonttech** [comment]
Is it something that can be added to the settings file or does it require a code change?

**Comment by ihsoft** [comment]
Nope, it's in the code.
