### ISSUE TITLE
When KIS is installed, the mass of command parts is drastically increased---Please merge with issue #29

### ISSUE THREAD

**Issue by svm420** [ihsoft/KIS#32]
Anyway, for the affected parts, Ablative Shielding and Monoprop are added twice to the mass of the command part, instead of only one time.
Thus eg a command part with a mass of 2 tons dry and 2.8 tons with monoprop and ablative shielding now has a mass of 2.8 tons dry and 3.6 tons wet.

MK1 command pod (stock)
with KIS: 0.880tW 0.840tD detail: 0.84t 
Without KIS: 0.84tW 0.800tD

MK2 lander can (stock)
With KIS: 2.820tW 2.660tD detail: 2.66t
without KIS: 2.660tW 2.500tD

Taurus HCV
With KIS: 8.700tW 8.100tD detail: 8.1t
without KIS: 8.100tW 7.500tD

S2 reusable pod (B9)
With KIS: 3.660tW 3.580tD detail: 3.58
Without: KIS: 3.580tW 3.500tD

**Comment by Delliardo** [comment]
Do you think you could test this with a fuel tank?  https://github.com/KospY/KIS/issues/29
If it is resource related, then we could probably get our issues combined.

**Comment by svm420** [comment]
It does seem to be the same issue. KIS adds the weight of any resource to a part with an inventory present even with the resource removed. i.e. pod wieght w/o KIS 2t+120kg MP: with KIS 2.12t+120Kg MP. Hope that makes sense.

**Comment by smjjames** [comment]
I'm just gonna note that the data in the OP above is actually from my post. Not really complaining, just making note of it for purposes of the issue report.

**Comment by KospY** [comment]
Fixed in 1.0.2. Releasing the update now as it's critical.
Thx for your help :)
