### ISSUE TITLE
Text formating in PAW menu

### ISSUE THREAD

**Issue by TonkaCrash** [ihsoft/KIS#326]
KSP 1.7, KIS 1.19, en-us localization. In flight the per seat inventories text label is poorly formatted on parts. They have the form  **"of a Name Inventory"**  instead of just **"Name's Inventory"**. Note the possessive "s" is missing in addition to the leading "of a" or "of an". The EVA inventory is fine. This is new behavior, it wasn't obvious to me what was wrong in the code.

See the following image: https://i.imgur.com/mfp9yrk.png

**Comment by ihsoft** [comment]
It seems Lingoona version has changed in KSP 1.7, and now it treats "<<1>>'s" as "of a Name". Do you remember any place in the core game where notation "Name's"? I'll can check how they deal with it and fix the localization.

**Comment by ihsoft** [comment]
Figured. It's indeed a change in Lingoona. Fix is simple. In the localization string `#kisLOC_00030` the _apostrophe_ symbol needs to be replaced by a _back single-quote_ symbol.
```
#kisLOC_00030 = <<1>>`s inventory
```

 And it's likely not the only case.
