### ISSUE TITLE
KIS fails on every new DLC or major patch that changes kerbal models

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KIS#328]
Every time a new kerbal model is introduced (e.g. a new suite), `KIS` fails to update these models with the required modules. Instead of relying on the `MM` patches for the specific pre-built parts, go thru the parts with module `KerbalEVA` and add the models to any part that has this module. It's less transparent approach, but it's also less error prone.

**Comment by TonkaCrash** [comment]
I thought you were taking a break :)

**Comment by ihsoft** [comment]
I can read emails :)
