### ISSUE TITLE
Tweakscale compatibility.

### ISSUE THREAD

**Issue by enceos** [ihsoft/KIS#34]
Pellinor, the Tweakscale developer, is willing to collaborate to make his mod compatible with KIS.
He posted his ideas here: http://forum.kerbalspaceprogram.com/threads/113111-0-90-Kerbal-Inventory-System-%28KIS%29-1-0-2?p=1829590&viewfull=1#post1829590

**Comment by KospY** [comment]
Tweakscale compability added in KIS 1.1
