### ISSUE TITLE
Error at main menu just after starting game.

### ISSUE THREAD

**Issue by Galenmacil** [ihsoft/KIS#345]
[ERR 21:25:10.985] [Part:kerbalEVA_RD_Exp(Clone) (id=C0)] Unexpected part configuration: partConfig=<NULL>

[ERR 21:25:10.994] [Part:kerbalEVA_female_Exp(Clone) (id=C0)] Unexpected part configuration: partConfig=<NULL>

[ERR 21:25:10.994] [Part:kerbalEVA_RD_Future(Clone) (id=C0)] Unexpected part configuration: partConfig=<NULL>

[ERR 21:25:10.994] [Part:kerbalEVA_female_Future(Clone) (id=C0)] Unexpected part configuration: partConfig=<NULL>

Also, when EVA'ing a female Kerbal, a similar error is displayed.

[KSP.log](https://github.com/ihsoft/KIS/files/3429646/KSP.log)

**Comment by ihsoft** [comment]
The four error messages are Ok when no DLCs are installed. Do you have any?

**Comment by Galenmacil** [comment]
No. Plain KSP 1.7.3 no DLC. So this is normal... Ok then... Even during gameplay when EVAing a Female character?

**Comment by ihsoft** [comment]
It's not normal during EVA. The error is displayed for the kerbal models that are defined in the DLCs. If you don't have DLC, you cannot EVA with that model. How exactly do you reproduce this issue and what is the error message? I haven't found any in the log.
