### ISSUE TITLE
Some stackable items lose stackability

### ISSUE THREAD

**Issue by JoelleEmmily** [ihsoft/KIS#346]
JS-1 Joint Socket and TJ-1 Fixed Telescopic Joint were initially stack-able, and several storage container still contain stacks of these items, but the indicator for how many are in the stack has disappeared, and singles cannot be added to an existing stack. They can still be split however. This error persists during flight, as well as in the VAB. The BS-80 Electric Screwdriver and BS-K4 standard explosive stack properly however.

**Comment by ihsoft** [comment]
In order for KIS to stack items it must be aware of the modules on the part. It seems you've installed a mod that adds a new module to a wide set of parts. You need to figure out which mod it is and whitelist that module. See a relevant section in the config: https://github.com/ihsoft/KIS/blob/master/settings.cfg#L94.

**Comment by JoelleEmmily** [comment]
Please clarify, does blob-ification only occur when an unknown module is added to a previously stackable part, or when any custom module is added to the game regardless if the part in question is patched.

**Comment by JoelleEmmily** [comment]
I have found the issue. By checking the ModuleManager.ConfigCache file, I found that AmpYear was adding a module(moduleName = AYPart) to /almost/ ever part. White listing it has rectified the problem.

**Comment by JoelleEmmily** [comment]
I would strongly recommend adding the troubleshooting procedure of searching the cache file for an offending part, to determine if the part has been modified by other mod.

**Comment by ihsoft** [comment]
By a chance, can you make a mockup of such troubleshooting page? I will gladly add it to Wiki. Since you've been thru this already, you may give a good troubleshooting sequence :)

**Comment by JoelleEmmily** [comment]
**Kerbal Inventory System (KIS)
Support
How to install
Troubleshooting**

**No Longer Able To Stack Previously Stackable Item**

- Prior to modifying any game or mod files, make a backup of your save directory, and the file you are intending to modify. Please be aware that folders such as "saves" and "GameData", are always sub-directories of your Kerbal Space Program installation. The name of the main directory, or where that directory is located on your drive however, may vary depending on where you have chosen to install it.
- To function properly, KIS must be aware of all modules being applied to a part. If a part's behaviour has seemingly suddenly changed, find that part's unique name by searching for it within the GameData directory files. Please be aware, a part's unique name usually is not the same as its common name. For example, the "Mk1 Command Pod" configuration file is located at "\GameData\Squad\Parts\Command\mk1pod\mk1Pod.cfg", and is referenced as "mk1pod".
- When you have found the part's unique name, open "ModuleManager.ConfigCache" in the root of the KSP's GameData folder, and search for it. 
- When you have located the part's unique name in "ModuleManager.ConfigCache", for example "name = mk1pod", scroll down to look for module references, for example "MODULE { name = ModuleCommand }". It is very likely that there will be more than one module reference, and it may be beneficial to take note of them all.
- When you have determined the part's module references, check them against KIS's white list located in the "/KIS/settings.cfg" file, under the "StackableModule" reference. Entries will be listed as "moduleName = ModuleSAS".
- You may add custom modules such as "moduleName = AYPart" here.
- If you continue to have difficulties with part behaviour, restore backups; then open a ticket on the KIS Git Repository. Write a detailed explanation of the unexpected behaviour, and include any steps you have taken to rectify the problem. Attaching your "ModuleManager.ConfigCache" and "persistent.sfs" files may also be helpful.

**Comment by ihsoft** [comment]
Thanks! It's now in [Wiki](https://github.com/ihsoft/KIS/wiki/Troubleshooting#no-longer-able-to-stack-previously-stackable-item).
