### ISSUE TITLE
Transfer Kerbal Removes Inventory

### ISSUE THREAD

**Issue by helaeon** [ihsoft/KIS#35]
On KIS 1.0.2.
It seems if you transfer a Kerbal within a ship by using the transfer function introduced with .90 it does not take the Kerbal's inventory with them.

**Comment by smjjames** [comment]
I just noticed this as well, hopefully it gets fixed soon.

**Comment by KospY** [comment]
Didn't have this issue... Just checked ingame with a mk1 lander can, mk1-2 command pod and the hitchhiker storage. Transfering the kerbal move inventory as expected.
What is the step to reproduce this problem ?

**Comment by helaeon** [comment]
Looks like it's a bug with the Training Akademy from the MKS/OKS pack.
When you right click on that part it doesn't show the "Open Kerbal's inventory", then when moving out of that part to another it loses the inventory screen all together (window comes up, but no boxes or portrait of the new part, just a flat grey box)
This part is the only one without an IVA, maybe related?

**Comment by helaeon** [comment]
Added to the Training Akademy cfg:
INTERNAL
{
  name = Placeholder
}

like the Mk3 Shuttle Cockpit and that fixes it!

**Comment by KospY** [comment]
Thanks for the information. I use IVA internal to check seats, I think it's related. If no IVA the transfer method must crash. Adding internal node is the way to go. I will not rewrite the method for this special case. Internal need to be added to pod anyway (even if it's a placeholder).

**Comment by smjjames** [comment]
Have you checked with the MK3 stuff other than the MKS training academy?

**Comment by helaeon** [comment]
Any pod without an IVA is affected. I think the rest of the MK3 parts have them... but the inflatable crew habitat does not. You could add that piece of code into any cfg with crew capacity that is missing an IVA. Or, write a module manager patch that does it. I think
@PART[ \* ]:HAS[#CrewCapacity[ \* ],!INTERNAL[ ] ]:FINAL
{
  INTERNAL
{
  name = Placeholder
}
}
would do it but I'm not sure.

KospY is right that with 1.0 all stock parts with crew capacity should have an INTERNAL node, and mods should follow that as well.
