### ISSUE TITLE
Kerbal's jetpack reacts to the mouse when dragging item

### ISSUE THREAD

**Issue by KospY** [ihsoft/KIS#36]

**Comment by KospY** [comment]
It seem there is no way to disable the mouse control on eva. 
KSP HandleMovementInput() method use Input.GetMouseButton(0) instead of a GameSettings input, so the Input lock method cannot disable this control.

**Comment by KospY** [comment]
Unfortunatly, I think I can't do anything about that. 
Squad hard coded the mouse click to rotate the kerbal on eva.

**Comment by kitoma** [comment]
Could temporarily disabling the EVA RCS for the duration of the dragging be an option? Ugly, I know...

**Comment by KospY** [comment]
SetControlLock have no effect on this.
Anyway, I finally found a workaround, setting the variable jetpackDeployed to false disable the EVA RCS ! 
I added this solution for the next version :)
