### ISSUE TITLE
"Escape" is spelled wrong & missing comma

### ISSUE THREAD

**Issue by Orthethac** [ihsoft/KIS#38]
Can be seen when in flight when you choose a part from the inventory and get ready to place it on the ground somewhere. In the explanation for the key bindings that pops up next to the part, "[Escape]" is spelled incorrectly as "[echap]".

Also, there is a comma missing after "orientation".

Full text: "(Press [Q][E] / [W][S] / [A][D] to rotate, [Space] to reset orientation [R] to change node, [echap] to cancel)"

**Comment by KospY** [comment]
"Echap" is the french word for the keyboard key "Escape" ;)
Seem like I wanted unconsciously to put French in KIS... I fixed the error in 1.1.1

Edit : I just realized that I forgot to fix comma missing after "orientation"...
Well that will be fixed for the next update.

**Comment by Orthethac** [comment]
Another one for you! For the helmet in the Kerbal's inventory, it says "Remove Helmet", which is fine. But then it says "Put Helmet". It should be "Put On Helmet" (or "Put Helmet On"). ;)

**Comment by KospY** [comment]
Thx ! I add this to the list.
English is not my mother tongue so there must be a lot of error like this...
Don't hesitate to report me any incorrect sentence and/or spelling error !

**Comment by Orthethac** [comment]
If I find any more, I'll post them here! Those are the only mistakes I noticed so far though.

**Comment by KospY** [comment]
Fixed in KIS 1.1.2
