### ISSUE TITLE
Part Duplication Bug with Vanilla Inventory

### ISSUE THREAD

**Issue by MystLeissa** [ihsoft/KIS#386]
As a part of the update to 1.11 I noticed something wrong with the KIS/Vanilla Interfacing, if you drag a part from the vanilla part storage into the Kerbal's inventory it effectively duplicates the item in-situ because it doesn't lower the count of the item IN the cargo part from vanilla. 

Suggested Remedies:

A. Disable Inventory Systems Interaction (No Vanilla v. KIS Interactions)

B. Reduce the Count on Cargo Parts when removed from Vanilla Storage.

Also this bug was discovered as a part of a unrelated bug where the Vanilla "Construction System" was disabled (i had used both inventory systems not realizing the Kerbals wouldn't be able to attach the vanilla system parts)

**Comment by ihsoft** [comment]
What is "Vanilla". Is it a mod or do you refer the new stock inventory system in KSP 1.11? If the latter, then there should be no interactions at all. In the latest update (v1.28) all the KIS dialogs get disabled when the stock construction mode is activated. And I don't see a way to move items between the stock and KIS inventories. Could you please make a short video to demonstrate it?

**Comment by MystLeissa** [comment]
I'm referrring to the stock inventory system; I need to test with the latest version but...when I dragged and dropped a part from KIS to the Stock Inventory (on a command pod, not in construction mode) it duplicated the item. It's basically when transferring from KIS to Stock/Vanilla Inventory without construction mode (e.g. Dragging and Dropping) I'll work on the video but no promises

**Comment by MystLeissa** [comment]
Wouldn't you know it - I can't reproduce it now...guess it was a one-off.
