### ISSUE TITLE
Allow Ground Base to be removed

### ISSUE THREAD

**Issue by Goldenpsp** [ihsoft/KIS#42]
With KAS, the Ground pylon was able to be removed without restriction.  This was often useful for assembling items by being able to assemble using the ground pylon as an "anchor" and then removing it at the end, such as building a Rover from parts.  This helped greatly with the parts falling through the ground or exploding issues.

With the KIS Ground base however this does not seem possible.  At the end of the process I get an error that I cannot grab or remove the ground base as it has other items attached to it.

**Comment by ghost** [comment]
This would be a huge improvement, as it would allow to effectively build rovers or small vessels on  other planets.  It is really tricky to do that right now as the parts may explode or jump around, probably because of KSP physics,

**Comment by KospY** [comment]
For information, a detach function for the wrench and the screwdriver is planned for 1.2.

**Comment by Benargeez** [comment]
Would having a decoupler or 2 docking ports between the rover and pylon fix the issue? Build the rover and then detach it by conventional means.

**Comment by Goldenpsp** [comment]
Benargeez, yes that is an effective workaround.  I was just hoping to have the ground pylon function like it used to via KAS, where you can just pull it out from the bottom when done.  This also goes to the larger difficulty with KIS when trying to remove anything that has "more than one thing attached to it" (not remembering the exact error at the moment)

**Comment by KospY** [comment]
Released KIS 1.2.0. You can now detach any part without restriction :)
