### ISSUE TITLE
ModuleKISItemEvaPropellant weirdness

### ISSUE THREAD

**Issue by kitoma** [ihsoft/KIS#45]
When setting "equipMode = part" and then using the Refuel function, the fuel values of the part as shown ingame(stock) and in the inventory(KIS) are out of sync.

How to reproduce:
- edit the KIS_evapropellant.cfg , set ModuleKISItemEvaPropellant.equipMode = part
- put the EVA fuel bottle into Jebs inventory, go to EVA, equip bottle
- waste some fuel
- use the refuel
- compare the EVA fuel values shown in the KIS inventory (now reduced) to the values shown when rightclicking the item (100% full)
- unequip the item, again check the values in the KIS inventory (100% full)
  = unlimited EVA fuel

Background: I have a composite part which I previously used with KASModuleGrab which contains some EVA fuel, a battery and _stuff_; thought I would give it a try to convert it to ModuleKISItemEvaPropellant , but observed said weirdness.

**Comment by KospY** [comment]
Fixed in KIS 1.1.3
