### ISSUE TITLE
ship exploding when attaching parts deep in space

### ISSUE THREAD

**Issue by cordilon** [ihsoft/KIS#48]
After attaching just a single part via KIS far from a planet my ship (no matter how complex afaik) would stay calm for a few seconds and then completele disintegrate in most cases with parts flying away in all directions. Sometimes the force that seems to be applied is more gentle and the ship will just start to spin wildly.
No other mods installed besides HyperEdit, but the issue occured without it, too.

KSP v1.02 32bit (manual install from store) and KIS v.1.1.2 were used.
To recreate
- get a ship deep into space (for example 1.000.000.000km above Jool)
- get an Engineer on EVA
- equip a screwdriver
- put a part (solar panel, battery, etc.) in your inventory or grab an existing one from the ship
- attach the part anywhere to your ship
- wait a few secs

I made a video for convenience and added the save file and output log here:
https://www.dropbox.com/sh/732efmbfbi7453j/AABQm1dS3i1olavWlJzSsobxa?dl=0
The sounds heard were actually like that in the game.

My machine: Intel i7 2600K on ASUS P8H77-V motherboard with 16gb DDR3 RAM by Kingston. GPU is a Nvidia GTX770 OC by Gigabyte. My OS is Windows7 64bit Service Pack 1.

**Comment by KospY** [comment]
Thanks for your detailed explanation ! I just replicated the issue on my game and unfortunatly my last update did not fix this. :(

**Comment by cordilon** [comment]
No problem =) Do you have an idea, what's causing it?

**Comment by KospY** [comment]
Seem like a velocity reset. If I remove the joint after attaching, the part disappear because of the different velocity. Velocity is so high that it broke the ship !
I'm trying to use a new method without the need to decouple and couple the part after his creation (seem to be the cause)

**Comment by cordilon** [comment]
That sounds awesome. Thanks for looking into it!

**Comment by KospY** [comment]
Finally found a way to fix this. Decouple/Couple seem mandatory so I delayed the couple action after the part was initialized as I did before. I however re-arranged the code to merge the fix about kerbal velocity reset too. Tested in kerbin orbit, minmus orbit and jool "deep space". No problem so far !
Released KIS 1.1.4.

**Comment by cordilon** [comment]
Nice. I'll put the new version through some testing myself as soon as it's online.
