### ISSUE TITLE
Hologram ignores rescaleFactor when used from Inventory

### ISSUE THREAD

**Issue by pellinor0** [ihsoft/KIS#53]
I defined an enlarged part using the 'rescaleFactor' config value. When taking it out of an Inventory the hologram shows the unscaled part. Once placed for the first time, the part has the right size and afterwards also the hologram is right. 

+PART[AES_Beam]  // larger version (no TweakScale so it stays KIS-stackable)
{
    @name = AES_BeamLarge
    @title = AES Structural Beam (Large)
    @rescaleFactor = 2
    @mass *= 4
    @cost *= 4
}

**Comment by KospY** [comment]
I tested this and it work fine for me, adding "rescaleFactor = 5" to the bomb for exemple show the hologram correctly sized.
Are you sure to use the latest version ?

**Comment by pellinor0** [comment]
Testing on 1.1.5, I can confirm that it is not a general KIS issue. The bomb works fine for me, however the AES beam still behaves as described. 

For now I'll blame my modded install, and report back if I find out more. What is special about the AES beam (from the USI exploration pack) is that the cfg contains multiple MODEL{...} nodes.
