### ISSUE TITLE
Game crash in combination with tweak scale

### ISSUE THREAD

**Issue by Chaia** [ihsoft/KIS#58]
-Scale your KIS container bigger with tweakscale
-Fill it up with random stuff
-Scale KIS container so small, that the stuff inside wouldn't fit anymore

Then the game crashes.

The container should only be tweak-scale-able if they are empty, or they delete their inventory upon being tweaked smaller, if it wouldn't fit anymore

**Comment by KospY** [comment]
This need to be adressed by tweakscale. 
I cannot prevent rescaling from KIS.
