### ISSUE TITLE
Conflict with Seat and standard KIS inventory on command pods?

### ISSUE THREAD

**Issue by Goldenpsp** [ihsoft/KIS#59]
Apologies if this has been brought up, but I believe a bug has been found. It seems there is something amiss when dealing with a Command pod that also has KIS storage. When you have a craft with 2 command modules (say after docking) and use the KSP gui to transfer a kerbal from one command pod to another, the kerbals personal inventory wipes out the command pod's main inventory.

Here is what I did to reproduce the issue.
1. Took a stock KSP installation. Added KIS and KAS.
2. Made a new part cfg based off the Mk1 lander can, and added 1000 KIS storage to it using ModuleKISInventory.
3. Made a basic setup with essentially the Lander can, probe core wheels and a KAS pipe end. I put various items into the kis inventory only. I drove one unmanned off the launchpad. I made a second craft with the same setup, except this time i put some different items in inventory just so I could tell teh difference. I also added Bill to this one.
4. I drove the second craft over to the first. EVA'd bill, grabbed a drill out of the lander can and equipped on bill. Connected the 2 crafts via the KAS pip. Got bill back into the command pod he had been in originally.
5. I then checked the inventory of both command pods to verify they had not changed. All looked good.
6. I then transferred bill to the other command module using the transfer button.
7. I then checked the KIS inventory again. This time the inventory of the command pod I had transferred bill to, only had bills Drill. All of the other items previously in inventory was gone.

**Comment by KospY** [comment]
Does it only happen when a KIS storage is added on the command pod ?

**Comment by Goldenpsp** [comment]
Oh geez, it has been a long time since I tested this.  If I remember correctly yes it is an issue if KIS storage is added to a part that is a command pod.  Tested with some mod parts as well as stock command pods.  it only happens if you use the built in transfer feature to move kerbals between command pods vs EVA'ing them over.

**Comment by KospY** [comment]
Thanks for your reply. I will take a look ;)

**Comment by KospY** [comment]
I think it's related to pod without internal. This problem will be fixed in the next version of KIS.
