### ISSUE TITLE
Docked "KIS made" rover doesn't "survive" save

### ISSUE THREAD

**Issue by Kushulain** [ihsoft/KIS#63]
I made a little rover on Minmus using KIS. I can dock/undock it to my outpost, no problem. But if I save and load the game back while the rover is docked, I won't be able to undock it correctly, when I click Undock  :
- It throws a nullReferenceExecption
- Cut my rover into 2 pieces (one stays static, the other behaves as if it were in zero gravity)
- And come a bunch of other bugs.

https://www.dropbox.com/s/716r4ek4q8eqgxh/kerbalUnDockBug.jpg?dl=0

Except for that, I had a lot of fun with your mod, keep it up. Thank you a lot !

**Comment by KospY** [comment]
Can you send me your KSP log file when it happen ?
Did you try without any others mods ?

**Comment by Kushulain** [comment]
Well, I'll need to build a new ship to test it without any other mods. But the only other mod i use is KerbalEngineer, wich shouldn't interfer with all this imo.

Here is the full log (start the game, dock my rover, quicksave, quickload, undock) : 
https://dl.dropboxusercontent.com/u/57159442/KSP.log

Error at Undocking (Line 2431 in the log) :

[EXC 19:38:13.803] NullReferenceException: Object reference not set to an instance of an object
    PartJoint.SetupJoint (Vector3 jointPos, Vector3 jointOrt, Vector3 jointOrt2, Int32 size)
    PartJoint.create (.Part child, .Part parent, UnityEngine.Transform nodeSpace, Vector3 nodePos, Vector3 nodeOrt, Vector3 nodeOrt2, Int32 nodeSize, AttachModes mode)
    PartJoint.Create (.Part owner, .Part parent, .AttachNode nodeToParent, .AttachNode nodeFromParent, AttachModes mode)
    Part.CreateAttachJoint (AttachModes mode)
    Part.SetHierarchyRoot (.Part root)
    Part.SetHierarchyRoot (.Part root)
    Part.Undock (.DockedVesselInfo newVesselInfo)
    ModuleDockingNode.Undock ()
    BaseEvent.Invoke ()
    UIPartActionButton.OnClick ()

I then left the ship with my kerbal, and climbed back in the rover, the camera then focused on the big ship instead of the rover (as they were still docked)

I tried to use RCS, it threw errors as well (line 2452-2504).
I tried to undock again 3 times and it threw 3 errors line (2513-2523).

I hope it helps. Would be great to test it more, to see if it's just a rare exception.
Good luck with all that !

**Comment by ihsoft** [comment]
This issue is likely fixed by a set of refactoring changes to the nodes (de)couple functionality.
