### ISSUE TITLE
Error message when using kis and playing sound

### ISSUE THREAD

**Issue by cfloutier** [ihsoft/KIS#64]
![capture d ecran 2015-06-12 13 56 25](https://cloud.githubusercontent.com/assets/11272483/8129584/f63a6666-110a-11e5-85e5-1bdc1b1b1537.png)

and of course no soudn. 
that's really minor bug ...
Or perhaps I sould move sound to another directory

**Comment by KospY** [comment]
Are you running KSP on linux ?
Did you put KIS in gamedata\KIS ?

**Comment by cfloutier** [comment]
sorry i've missed your message.
No more error. it's my mystake. I've put kis in the yrong directory....

2015-06-26 18:17 GMT+02:00 KospY notifications@github.com:
