### ISSUE TITLE
Game crashes after some time when KIS is installed

### ISSUE THREAD

**Issue by LukaDavidTorkar** [ihsoft/KIS#65]
I installed KIS a day ago and since then it keeps crashing after about an hour. When I revert to editor all the parts on the left are missing. Sometimes when I try to exit the editor the game crashes. I didn't had this issue before. Also the launch towers from the fasa pack are jumping after my rocket when it's asending. Sometime they even folow me to space.

**Comment by KospY** [comment]
Can you send me your KSP log file when the game crash ?

**Comment by LukaDavidTorkar** [comment]
Sorry. I deleted it :(. It was the same meseage that you get when you reach the ram limit. The point is that i didn't even get to 2 GB. Normaly the game crashes when I reach 3.5 GB. The install was not just stock so maby I had mods that are incompatible with kis. I created a new build using ckan and now it's working properly. I had some crashes but no missing parts or textures. :)

**Comment by space-is-hard** [comment]
@LukaDavidTorkar
RE: Launch tower issue

This is a known bug that's unrelated to KIS. https://www.reddit.com/r/RealSolarSystem/comments/3auw07/launch_clamp_bug/csg89n0
