### ISSUE TITLE
Add small inventory space in stock probes and/or pods or more container sizes

### ISSUE THREAD

**Issue by Benargeez** [ihsoft/KIS#69]
It would be nice to have a small space to store tools on a small space craft without having to hang a storage container off the side. For example, I want to send a wrench to an engineer I have on minmus. I would like to do so without sending another Kerbal or making my craft bigger just for a tiny little wrench!

Since I am also sending an empty pod for their rescue I would like to store a wrench in there so that the engineer can retro fit somethings before coming back. Its not unreasonable to store a tool inside a pod that can fit a kerbal.

Option 2:
Make more containers. It would be nice to have a round inline 1.25m container and an inline 0.625m inventory container.

**Comment by sardia** [comment]
Have you tried adding the storage container onto the nose of the rocket?

**Comment by ihsoft** [comment]
Checkout `IMiC-1500`
