### ISSUE TITLE
Modules that should be stackable.

### ISSUE THREAD

**Issue by enceos** [ihsoft/KIS#72]
Would it be possible to make stackable all parts which have neither resources nor modules?

**Comment by KospY** [comment]
It's already the case. If structural parts do not stack, you must have a mod that adds modules on those parts.
You can add those modules in the StackableModule node in the settings.cfg if needed however.

**Comment by enceos** [comment]
I see, thanks, from the MM cache I found that every structural part on my install has these modules:

> ```
>     MODULE
>     {
>         name = ModuleAGX
>     }
>     MODULE
>     {
>         name = TweakScale
>         type = free
>     }
>     MODULE
>     {
>         name = USI_ModuleRecycleablePart
>         Menu = Scrap Part
>         ResourceName = Recyclables
>         Efficiency = .8
>     }
>     MODULE
>     {
>         name = USI_ModuleRecycleablePart
>         Menu = Salvage Part
>         ResourceName = SpecializedParts
>         Efficiency = .4
>     }
>     MODULE
>     {
>         name = EnhancedThermalDataModule
>     }
> ```

**Comment by enceos** [comment]
The mods which add these modules to every part are: [Action Groups Extended](http://forum.kerbalspaceprogram.com/threads/74195), [Hot Spot (formerly Enhanced Thermal Data)](http://forum.kerbalspaceprogram.com/threads/123967) and obviously [TweakScale](http://forum.kerbalspaceprogram.com/threads/112693). Do you think you can include them to the default settings? Probably excluding TweakScale.

**Comment by SirDiazo** [comment]
Action Groups Extended author here. My mod should actually do this already via the KISConfig.cfg moduleManager patch file that resides in the AGExt directory. (The ModuleAGX partModule is mine.)

If this is not working for the ModuleAGX partModule, I would ask you file a bug report for AGX about it.

**Comment by enceos** [comment]
@SirDiazo I see, then I'll get to the Hot Spot author with your example.

**Comment by enceos** [comment]
@KospY Continuing the issue, what do you think about adding these stock modules to the default list? They look very stackable to me:

> ```
>     moduleName = ModuleRCS
>     moduleName = RetractableLadder  
>     moduleName = ModuleDeployableSolarPanel
>     moduleName = ModuleDeployableRadiator
>     moduleName = ModuleActiveRadiator
>     moduleName = ModuleLandingLeg
> ```

**Comment by KospY** [comment]
@enceos : I added your list to the next version of KIS, thanks :)
