### ISSUE TITLE
Node attach for some radial part is broken

### ISSUE THREAD

**Issue by Brusura** [ihsoft/KIS#73]
I can not re-attach once detached part for some radial parts, ie:

Cubic Octagonal Struct

BZ-52 Radial Attachment Point

Steps to reproduce:

while in game detach a part and try to attach it to the node of a radial part ie BZ-52

**Comment by KospY** [comment]
Tried it and it work for me?
I did this : 
- Taken a BZ-52 from inventory
- Attach it with the surface node on the ISC-6K container
- Taken a container and attach it on the BZ-52 (I also tried with other parts like the Cubic Octagonal Struct)

**Comment by Brusura** [comment]
Hi Kospy the BZ-52 is already attached, build in the vab something like this:

Mk1 Lander Can ( node attached to BZ-52 )
BZ-52 ( surface attached to Mk2 Lander Can )
Mk2 Lander Can ( root part )

When launched detach the Mk1 Lander Can and try to reattach it on the BZ-52 node, you cant but you can attach the Mk1 Lander Can to the Mk2 Lander Can's node

**Comment by KospY** [comment]
That really strange, it didn't work because the "attachedPart" variable of the BZ-52 top node is set to  "trussPiece1x" when the part is loaded and attached from the editor.

**Comment by KospY** [comment]
Thanks for your report.
I managed to fix this issue :)
It will be included in the next update.
https://github.com/KospY/KIS/commit/62623c0a2617ae53a78cc3d26fa0c90f1b600bf6

**Comment by Brusura** [comment]
Glad to help you :)
