### ISSUE TITLE
Universal Storage - sc-9001 Science Jr not recognized as material bay by missions

### ISSUE THREAD

**Issue by mblob** [ihsoft/KIS#79]
hi,

![screenshot10](https://cloud.githubusercontent.com/assets/967684/8967944/b2fcf7ba-363a-11e5-8655-47ed3cdde96c.png)

I guess screenshot is self-explanatory.

**Comment by Kerbas-ad-astra** [comment]
Are you sure this is the right repo? I'm pretty sure DMagic Orbital Science is the one which adds the US Materials Bay.

**Comment by mblob** [comment]
Not related to your mod but dmagic orbital science. sry
