### ISSUE TITLE
Can't use thermometers (and other science) without attaching them

### ISSUE THREAD

**Issue by AkashaRepo** [ihsoft/KIS#84]
It used to be possible to use a Thermometer (or other small science part) while it was being carried on a Kerbal's back in EVA. Now that is no longer possible and you cannot activate them from the inventory.

This means Kerbals can't do science on EVA unless there is a convenient surface to attach things too. Also, dropping small objects like Thermometers seems to always destroy them, even in Munar gravity.

**Comment by enceos** [comment]
I drop them on Kerbal's head :) works great

**Comment by Kerbas-ad-astra** [comment]
[**MonkeyWrench**](https://github.com/WarrenSchultz/MonkeyWrench) has some configs (updated from KAS to KIS by yours truly) that add KIS modules to small science instruments so that they can be equipped and used without dropping them.

**Comment by ihsoft** [comment]
Parts stored in a KIS container don't exist as game objects. And making any science part to be equippable sounds as an overkill.
