### ISSUE TITLE
Detaching parts grabbed by a gapling node produces bugs everywhere.

### ISSUE THREAD

**Issue by enceos** [ihsoft/KIS#86]
Original forum post describing the problem:
http://forum.kerbalspaceprogram.com/threads/113111-1-0-4-Kerbal-Inventory-System-%28KIS%29-1-2-2?p=2164845&viewfull=1#post2164845

Possible solutions:
1) Disallow detaching parts grabbed by the graplers with MODULE [ModuleGrappleNode].
2) Force release the part by the grappler after it has been detached via tools.

**Comment by ihsoft** [comment]
The forum's link doesn't give any concrete post.

In general, detaching from a docking port works bad in KIS since ports have active scripts on the connection. ModuleGrappleNode is just a special case of this issue. A generic way of stopping port's script needs to be found.

**Comment by ihsoft** [comment]
Handling of the docking nodes has been improved dramatically. However, it could not fix this particular issue. Feel free to re-open when more details are available.
