### ISSUE TITLE
Lag When Clicking on a Part

### ISSUE THREAD

**Issue by ATRealMaster** [ihsoft/KIS#87]
If I go to the launch pad, then return to the VAB, everytime I click on a part, it freezes for a few seconds, and then I can attach it. If I try to launch, then go back Again, it will freeze for even longer.

It is the KIS's Issue. I uninstalled everything except KIS and tested it. I tried making a new save file but it still doesn't work.

Here is the output_log(too big for pastebin): https://www.mediafire.com/?258a77f2g96c167

Any Help Will Be Appreciated!

**Comment by ihsoft** [comment]
+1
I observe the same issue.

**Comment by ihsoft** [comment]
Released in v1.2.4
