### ISSUE TITLE
Portable containers revert to previous content when dropped.

### ISSUE THREAD

**Issue by KolnIV** [ihsoft/KIS#89]
A container that was on the ground and now is carried by a kerbal will revert to the content that it had on the ground if it is dropped by the kerbal.

Steps to reproduce:

-Put a container on the ground.
-Load it on a kerbal.
-Change the content of the container.
-Drop the container by right-clicking on it in the kerbal's inventory.
-Now the content is the same as it was before loading it on the kerbal.

Parts added to the container disappear, and part that were taken from it now appear in it again and staying wherever you moved them. I've lost parts with this and after finding how to do it I've created them again with it.

It has happened to me with stock parts (1x6 solar panel, docking port jr, cyllindrical monopropellant tank). I haven't tried with other modded parts, but I don't think it has anything to do with other mods. Here's my list of mods in any case:

-Active Texture Management
-Contracts Window
-Distant Object Enhancement
-Engine Light
-EVE
-Hull Camera
-KAS
-Kerbal Engineer
-KJR
-KIS
-AVC
-Docking port alignment indicator
-RCS Build Aid
-RealChute
-Science alert
-Ship Manifest
-Stage Recovery
-TAC fuel balancer
-TAC life support
-Texture Replacer
-Alarm Clock
-Universal Storage
-WASD editor camera

**Comment by ihsoft** [comment]
Yes, it is reproducible.

One of possible solutions (and the easiest one) would be disallowing access to the container being carried. Updating serialized state in the kerbal's container may be tricky.

**Comment by ihsoft** [comment]
It's fixed as a bug: access to the carried inventories is restricted to prevent items loss.

I keep this issue opened as enchancement. It should be invetigated if it's feasible to try mangling with the persistent state of an inventory.

**Comment by ihsoft** [comment]
Now the carriable containers can be used to store or pull out the items.
