### ISSUE TITLE
Grab and Attach Function Not Working.

### ISSUE THREAD

**Issue by BorealisPhoenix** [ihsoft/KIS#90]
I know one would think that maybe I didn't RTFM but, I did. move object from kerbal inventory hold G or H then click. Doesn't work I click and nothing happens I can some times click over and over and out of no where the object will attach after I give up clicking and just hold H but, I have only grabbed something once in all the time I have played with this mod. I can't figure out if I have installed something wrong or if the lack of a gaming GPU causes some kind of grabbing lag that it only sometimes catches up to do the action. I would love to know what is going on.

**Comment by BorealisPhoenix** [comment]
I'd like to point out after the fact, to cover any other questions of do I know what I am doing, I have a wrench equiped. The grab and attach only work once every 50 tries. I don't know if it matter but I am using a touchpad, so it maybe possible that holding a G or H while clicking is something my computer can't do. If so is it possible to have some kind of option added for people that can't?

**Comment by BorealisPhoenix** [comment]
Ok So after some doing I figured out the issue. I'd like to leave this here some people that have and issue too can easily figure it out.

Not being able to move your mouse while holding a key is a synaptic settings issue (program for your touchpad in the bottom right of your desktop it's a little different for everyone. The fact that I couldn't hold a ket and click at the same time is a windows 8.1 and up issue. that's fix this way:

PC Settings > PC and Devices > Mouse and Touchpad > Touchpad

There is an option that reads: "To help prevent the cursor from accidentally moving while you type, change the delay before clicks work."

I may be the only person to use a laptop without a mouse while gaming but what can I say, mouse doesn't work well on my mattress. :D this is the first time I had a program need this button combo.

Great mod!

Hope this helps someone

**Comment by ghost** [comment]
You are a life saver!!! I don't know how you figured this out, but wow, I would have never found that out if it wasn't for this thread XD

**Comment by BorealisPhoenix** [comment]
Glad I could help.
