### ISSUE TITLE
Mass makes EVA near impossible to control

### ISSUE THREAD

**Issue by zeroinformatique** [ihsoft/KIS#91]
When you are wearing a box on your back, the game tries to compensate the inertia with RCS all the time, rolling out of control.

I would really appreciate a mass multiplier in KIS settings, or something equivalent to have more "gameplay" than "realism".

**Comment by Brusura** [comment]
Or additional RCS thrusters on the box to compesate for the offset mass

**Comment by ihsoft** [comment]
The KIS carried parts are equipped in mode "part", which doesn't result in any physics changes.
