### ISSUE TITLE
Contracts are reset with linking two vessels

### ISSUE THREAD

**Issue by zeroinformatique** [ihsoft/KIS#95]
I often use KAS/KIS to link vessels together with resource pipes. When you do this, both vessels are "merged" together by KAS/KIS, but this merge corrupts the vessel's UID and name. As soon as you unlink both vessels, when you look at the contracts, everything you did with the detached vessel is lost.

To compensate for this bug, I validate the contracts manually with ALT+F12, but it doesn't feel proper.

An idea: I love how the Stock clamp link two objects together with doesn't merge them (they are still separate entities). I would be awesome that KAS/KIS did a similar link without merge.

**Comment by ihsoft** [comment]
Main idea of KAS pipes is linking two vessels into one. Though, adding another kind of pipe that don't merge the vessels and only allow transferring fuel may be a good idea.

**Comment by ihsoft** [comment]
This is a feature for KAS. The new KAs will have a resource pump part.
