### ISSUE TITLE
Allow Attachment of Parts with Children

### ISSUE THREAD

**Issue by svm420** [ihsoft/KIS#96]
As the title states. I would love to be able to attach part that already have other parts attached to it. We are now able to detach parts with children, so I hope this would be possible as well. I want to be able to add girder segments to my station that have lights in 3x symmetry attached that I would have to hand place one by one as an example. Didn't see the issue posted, so I'll close it if this is open elsewhere. Thanks!

**Comment by ihsoft** [comment]
I'm working on this solution and pretty close to finishing with it. Moving of a hierarchy of parts is very different from moving of just a single part. There are many caveats. Expect to see a complete solution in teh following week.

**Comment by ihsoft** [comment]
[Alpha version](https://github.com/ihsoft/KIS/releases/tag/v1.2.3-alpha) is ready. Though, until author of the addon approved and integrated the change it should be considred "alpha".

**Comment by svm420** [comment]
Wow going to try this now Thank you so much!

**Comment by ihsoft** [comment]
Released in v1.2.4
